import { ForwardRefExoticComponent, RefAttributes, CSSProperties } from "react";
type IIconProps = {
    style?: CSSProperties,
    spin?: boolean
}

export declare const IconArrowDown: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconArrowFall: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconArrowLeft: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconArrowRight: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconArrowRise: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconArrowUp: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCaretDown: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCaretLeft: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCaretRight: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCaretUp: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconDoubleDown: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconDoubleLeft: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconDoubleRight: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconDoubleUp: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconDownCircle: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconDown: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconDragArrow: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconExpand: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconLeftCircle: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconLeft: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMenuFold: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMenuUnfold: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconRightCircle: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconRight: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconRotateLeft: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconRotateRight: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconShrink: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSwap: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconToBottom: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconToLeft: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconToRight: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconToTop: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconUpCircle: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconUp: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconAlignCenter: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconAlignLeft: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconAlignRight: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconAttachment: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconBgColors: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconBold: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconBrush: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCopy: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconDelete: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconEdit: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconEraser: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFilter: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFindReplace: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFontColors: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFormula: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconH1: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconH2: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconH3: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconH4: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconH5: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconH6: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconH7: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconHighlight: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconItalic: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconLineHeight: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconLink: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconObliqueLine: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconOrderedList: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconOriginalSize: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPaste: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconQuote: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconRedo: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconScissor: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSortAscending: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSortDescending: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSort: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconStrikethrough: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconUnderline: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconUndo: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconUnorderedList: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconZoomIn: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconZoomOut: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconChineseFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconEnglishFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFaceFrownFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFaceMehFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFaceSmileFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMoonFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPenFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSunFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconApps: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconArchive: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconBook: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconBranch: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconBug: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconBulb: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCalendarClock: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCalendar: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCamera: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCloud: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCommand: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCommon: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCompass: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCopyright: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconDashboard: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconDesktop: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconDice: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconDragDotVertical: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconDragDot: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconDriveFile: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconEar: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconEmail: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconEmpty: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconExperiment: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFileAudio: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFileImage: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFilePdf: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFileVideo: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFile: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFire: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFolderAdd: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFolderDelete: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFolder: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconGift: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconIdcard: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconImageClose: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconImage: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconInteraction: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconLanguage: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconLayout: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconLoading: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconLocation: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconLock: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconLoop: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMan: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMenu: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMindMapping: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMobile: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMoon: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMosaic: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconNav: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconNotificationClose: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconNotification: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPalette: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPen: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPhone: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPrinter: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPublic: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPushpin: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconQrcode: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconRobotAdd: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconRobot: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSafe: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSchedule: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconShake: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSkin: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconStamp: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconStorage: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSubscribeAdd: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSubscribe: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSubscribed: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSun: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconTag: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconTags: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconThunderbolt: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconTool: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconTrophy: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconUnlock: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconUserAdd: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconUserGroup: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconUser: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconVideoCamera: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconWifi: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconWoman: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconHeartFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconStarFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconThumbDownFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconThumbUpFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconAt: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCloudDownload: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCodeBlock: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCodeSquare: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCode: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCustomerService: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconDownload: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconExport: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconEyeInvisible: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconEye: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconHeart: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconHistory: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconHome: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconImport: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconLaunch: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconList: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMessageBanned: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMessage: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMoreVertical: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMore: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPoweroff: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconRefresh: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconReply: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSave: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconScan: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSearch: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSelectAll: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSend: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSettings: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconShareAlt: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconShareExternal: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconShareInternal: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconStar: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSync: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconThumbDown: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconThumbUp: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconTranslate: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconUpload: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconVoice: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconBytedanceColor: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconLarkColor: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconTiktokColor: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconXiguaColor: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFaceBookCircleFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFacebookSquareFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconGoogleCircleFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconQqCircleFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconTwitterCircleFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconWeiboCircleFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconAlipayCircle: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCodeSandbox: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCodepen: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFacebook: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconGithub: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconGitlab: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconGoogle: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconQqZone: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconQq: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconTwitter: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconWechat: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconWechatpay: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconWeibo: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMuteFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPauseCircleFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPlayArrowFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPlayCircleFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSkipNextFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSkipPreviousFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSoundFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconBackward: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconForward: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFullscreenExit: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconFullscreen: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconLiveBroadcast: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMusic: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMute: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPauseCircle: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPause: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPlayArrow: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPlayCircle: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconRecordStop: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconRecord: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSkipNext: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSkipPrevious: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconSound: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCheckCircleFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCloseCircleFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconExclamationCircleFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconExclamationPolygonFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconInfoCircleFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMinusCircleFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPlusCircleFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconQuestionCircleFill: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCheckCircle: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCheckSquare: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCheck: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconClockCircle: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconCloseCircle: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconClose: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconExclamationCircle: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconExclamation: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconInfoCircle: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconInfo: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMinusCircle: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconMinus: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPlusCircle: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconPlus: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconQuestionCircle: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconQuestion: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>
export declare const IconStop: ForwardRefExoticComponent<IIconProps & RefAttributes<unknown>>